services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning --maxmemory 256mb --maxmemory-policy allkeys-lru --appendonly no
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - mytheresa-network

  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=app
      - POSTGRES_DB=mytheresa
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    networks:
      - mytheresa-network
        
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "9003:9003"
    volumes:
      - ./api:/var/www/html
      - ./api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - mytheresa-network

  php:
    build:
      context: ./api/docker/php
    container_name: php
    volumes:
      - ./api:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://app:!ChangeMe!@db:5432/mytheresa?serverVersion=15&charset=utf8
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    networks:
      - mytheresa-network

volumes:
  db_data:
  caddy_data:
  redis_data:

networks:
  mytheresa-network:
    driver: bridge