
framework:
    cache:
        app: cache.adapter.redis
        #default_redis_provider: 'redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/0'
        default_redis_provider: snc_redis.api_kv_storage
        pools:
        #my.dedicated.cache: null
