nelmio_api_doc:
  documentation:
    info:
      title: MyTheresa - Search API
      description: Welcome to MyTheresa - Search API
      version: 1.0.0
  areas:
    default:
      path_patterns:
        - ^/products
